### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by Ppsj** [Ppsj/f2e-awesome-libs#4]
# CSS Variables

### 

### 使用

· 常规
· 状态

```css
.btn {
   --color: red;
   border-color: var(--color);
}
.btn:hover {
   --color: green;
}
```
· 断点
[DOME](https://hospodarets.com/you-might-not-need-a-css-preprocessor/demos/no-preprocessor-css-variables-media/)
```CSS
:root {
    --screen-category: 'desktop';
}

@media screen and (max-width: 1024px) {
    :root { --screen-category: 'tablet'; }
}

@media screen and (max-width: 640px) {
    :root { --screen-category: 'phone'; }
}

body:after {
    content: '--screen-category : 'var(--screen-category);
}
```
